In [ ]:
import numpy as np
from numpy.linalg import norm
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re
import os

In [ ]:
import tensorflow as tf
import tensorflow_hub as hub

from tensorflow import keras
import tensorflow_datasets as tfds

In [ ]:
module_url="https://tfhub.dev/google/universal-sentence-encoder/4"

In [ ]:
embedder=hub.load(module_url)

In [ ]:
def cos_sim(a,b):
  return np.inner(a,b)/(norm(a)*norm(b))

In [ ]:
# accepts answers without brackets
def embed(sentence):
  sentence_in=[sentence]
  
  return embedder(sentence_in)

In [ ]:
def find_mean(X):
  vectors=[]
  for element in X:
    vectors.append(embed(element))

  return np.mean(vectors,axis=0)

In [ ]:
def compare(response,targets,thres):
  a=embed(response)
  b=find_mean(targets)
  
  #dist=norm(a-b)
  return cos_sim(a,b),cos_sim(a,b)>thres


In [ ]:
group=['How old are you ?','What is your age?', 'When were you born?','What is your date of birth?','When is your birthday?']

In [ ]:
test='How old are you?'

In [ ]:
embed(test).shape

TensorShape([1, 512])

In [ ]:
compare(test, group, 0.5)

(array([[0.8083109]], dtype=float32), array([[ True]]))

## Collecting sample answers for all options

### Level1 Options

In [ ]:
# New Customer and Existing Customer

In [ ]:
existing_customer=['Yes','Yes I am','I have an account with you','yeah',
                   'I joined last year','since months ago','I have been a member since',
                   'Yes of course','I have a contract with you since', 'I am an existing customer']

In [ ]:
new_customer= ['No', 'I am a new customer', 'I don’t have any account','I want to open an account', 'I want to see your products and services', 
'I don’t have any contract with you', 'I want to move my sim card to your company', 'I would like to join your company',
'I want to know your available packages']

In [ ]:
test="I have a contract"

In [ ]:
compare(test, existing_customer, 0.5)

array([[ True]])

### Level 2 Options Branch1

In [ ]:
## New Customer

In [ ]:
new_contract=['I want to join','I want to see contract options','how long is the contract?']
products_services_info=['what services do you provide','what are your price plans','how much do calls cost?']
about_the_company=['tell me more about company','where are you based?','which area do you cover?']


### Level 2 Options Branch 2

In [ ]:
# about bill, account and more options

In [ ]:
about_bill=['I want to pay my bill','setup direct debit','my bill is too high', 'bill']
account=['I want to renew my contract','I would like to unlock my phone','upgrade my phone', 'account']
technical_issues=['low signal', 'my phone does not work','connection problem', 'technical issue']
more_options=['lost my phone','my phone was stolen','I want to ask about the delivery', 'more options']

### Level 3 Options - (about the bill, technical, more options)

In [ ]:
# about the bill
paying_the_bill=['I want to pay my bill', 'Can I pay my bill please', 'paying my bill' ]
set_up_direct_debit=['setup direct debit', 'I would like to setup direct debit','I want to pay bill by direct debit each month']
high_bill=['why is my bill too high','I got too high bill this month','the bill of this month is too high' ]

In [ ]:
# technical issues
about_the_phone=['my phone doesn not work','my phone screen is broken','my phone does not sound loud enough']
about_signal=['my internet connection is not very good','my internet connection is very bad. what can I do?','my internet does not work everywhere.' ]

In [ ]:
#other options
lost=["my phone is lost","I can't find my phone. I think it's lost ","I lost my phone. can you please help me? "]
stolen=["my phone stolen ","I can't find my phone since yesterday. probably stolen ","my phone was stolen in the cafe today "]
delivery=["how many days will my phone arrive", "I bought a new phone from you. When will it arrive?","where is my delivery "]

## Level 3 Options (Account)

In [ ]:
# account
contract=['I would an aditional contract','I would like another contract','I want to cancel my contract']
device=['I would like to upgrade my phone','could you help me to setup my phone','I want to move my information in old phone to new phone. How can I do it']
ac_more_options=['what are the roaming charges','how many free minutes do I have?','I want to leave the company.']

### Level 4 Options (contract, device, more options)

In [ ]:
# contract
additional_contract=['I want an additional contract','I want a second contract','is there a discount on a second contract']
renew_contract=['I want to renew my contract','if I renew my contract, how much discount will I get?','what options do I have for a new contract']
cancel_contract=['I want to cancel my contract','the contract is too expensive and I dont need it','I want to end my contract']

In [ ]:
# device
device_setting=['could you help me to setup my phone','I want to change my settings','I want to setup my voicemail']
upgrade_phone=['I want to get a new phone','how much is it to upgrade?','I want a more recent phone','Can I upgrade my phone?']


In [ ]:
# more options
check_allowance=['How many free minutes do I have?','what are my allowances?','how many gigabytes I have remaining']
leaving_us=['I want to leave your company','I want to move my number to a different network','I am not happy with this network']
additional_charges=['what are cost of calls to premium numbers', 'what are the roaming costs?', 'I want to use my phone abroad']
unlock_phone=['my phone is locked', 'I want to unlock my phone', 'could you unlock my phone please']


In [ ]:
customer='how many minutes do I have'
compare(customer, existing_customer,0.5)

array([[ True]])

In [ ]:
def add():
  print('how are you?')
#add=['I am fine']

In [ ]:
def a_charges():
  print('Please visit our website to see a list of additional charges for roaming, extra data bundle etc')
  print('Thank you for contacting us. Hope to see you again.')
  
def unlock():
  print('Your request to unlock has been recorded. Your phone will be unlocked within five working days.')
  print('Thank you for contacting us. Hope to see you again.')
  
def leave():
  print('We are sorry to see you want to leave. What can we do for you so you can stay')
  print('Thank you for contacting us. Hope to see you again.')
  
def allowance():
  print('Please call #3333* on your mobile to see your allowance')
  print('Thank you for contacting us. Hope to see you again.')
  
def upgrade():
  print('Please visit our website to see various deals with upgrade')
  print('Thank you for contacting us. Hope to see you again.')
  
def setting():
  print('Please call 333 on your phone to receive the default or select the relevant setting to change')
  print('Thank you for contacting us. Hope to see you again.')
  

def cancelC():
  print('We are sorry to know that you are not happy with continuing with our contract. Please call our special number 0345 67 87')
  print('Thank you for contacting us. Hope to see you again.')
def renewC():
  print('We are please to know that you can to stay with us. Your contract is renewed')
def additionalC():
  print('Please visit our website to see various option and buy a new contract from there.')
  print('Thank you for contacting us. Hope to see you again.')
#11
def stolenphone():
  print('Please report your stolen phone to the police and send us the crime number')
  print('Thank you for contacting us. Hope to see you again.')
def lostphone():
  print('If you suspect that your lost phone it was stolen, please report it to the police and send us a crime number')
  print('Thank you for contacting us. Hope to see you again.')
def deliveryQ():
  print('Please visit royalmail website and use your tracking number to check the progress of the delivery')
  print('Thank you for contacting us. Hope to see you again.')
def phoneissue():
  print('Please visit our website and book an appointment to bring it to one of our stores or send your device by post')
  print('Thank you for contacting us. Hope to see you again.')
def signalissue():
  print('Please note that our network had a technical issue and our technicians have been working hard to fix it. We will text you as soon as this is sorted.')
  print('Thank you for contacting us. Hope to see you again.')
def complaint():
  print('Please email your complaint to complaints@three.co.uk and send any relevant documents')
  print('Thank you for contacting us. Hope to see you again.')

def directdebit():
  print('Please visit our website and login to your account to setup the direct debit')
  
def pay():
  print('Please visit our website to pay the bill or call 0870 987658 and give your card details')
  print('Thank you for contacting us. Hope to see you again.')

def newcontract():
  print('Please go to our website and choose one of our deals or call our special number for new customers')
  print('Thank you for contacting us. Hope to see you again.')
def products():
  print('Please go to our site to read about all our products and service or visit our branch to get a leaflet')  
  print('Thank you for contacting us. Hope to see you again.')  
def aboutthecompany():
  print('Please visit our website to get all the information you need about our company')
  print('Thank you for contacting us. Hope to see you again.')

#1
def ac_moreoptions():
      
      print("Choose one of the following options so that we can help you.")
      userInput = ""
      answer1=''
      answer2=''
      answer3=''
      answer4=''
      while (answer1 or answer2 or answer3 or answer4)!=True:
        print("Options:Info about allowance, Leaving us, information about additional charges, Unlock the device")
        userInput = input().lower()
        answer1=compare(userInput,check_allowance,0.5)
        answer2=compare(userInput, leaving_us, 0.5)
        answer3=compare(userInput,additional_charges,0.5)
        answer4=compare(userInput,unlock_phone,0.5)
        
        if answer1 == True:
           allowance()
        elif answer2 == True:
          leave()
        elif answer3 == True:
          a_charges()
        elif answer4 == True:
          unlock()
        else: 
          print("I do not understand your response. Please rephrase")


#2
def deviceoption():
  print("How can I help you about your device?")
  userInput = ""
  
  answer1=''
  answer2=''
  
  
  while (answer1 or answer2 )!=True:
    print("Options:Settings, Upgrade")
    userInput = input().lower()
    answer1=compare(userInput, device_setting,0.5)
    answer2=compare(userInput, upgrade_phone,0.5)
    
    
    if answer1 == True:
      setting()
    elif answer2 == True:
      upgrade()
    
    else: 
      print("What is the issue about")


#3
def contractoption():
  print("How can I help you about your contract?")
  userInput = ""
  
  answer1=''
  answer2=''
  answer3=''
  
  while (answer1 or answer2 or answer3)!=True:
    print("Options:Additional contract, Renew contract, Cancel contract")
    userInput = input().lower()
    answer1=compare(userInput,additional_contract,0.5)
    answer2=compare(userInput,renew_contract,0.5)
    answer3=compare(userInput,cancel_contract ,0.5)
    
    
    if answer1 == True:
      additionalC()
    elif answer2 == True:
      renewC()
    elif answer3 == True:
      cancelC()
    else: 
      print("I do not understand your response. Please rephrase")

#4
def technical():
  print("Welcome to the technical department, how can I help you?")
  userInput = ""
  
  answer1=''
  answer2=''
  
  
  while (answer1 or answer2 )!=True:
    print("Options:about the phone, about signal")
    userInput = input().lower()
    answer1=compare(userInput, about_the_phone,0.5)
    answer2=compare(userInput, about_signal,0.5)
    
    
    if answer1 == True:
      phoneissue()
    elif answer2 == True:
      signalissue()
    
    else: 
      print("What is the issue about")
#5
def moreoptions():
  print("Could you please specify your problem")
  userInput = ""
  
  answer1=''
  answer2=''
  answer3=''
  
  while (answer1 or answer2 or answer3)!=True:
    print("Options:Stolen phone, Lost phone, Delivery")
    userInput = input().lower()
    answer1=compare(userInput,stolen,0.5)
    answer2=compare(userInput,lost,0.5)
    answer3=compare(userInput,delivery,0.5)
    
    
    if answer1 == True:
      stolenphone()
    elif answer2 == True:
      lostphone()
    elif answer3 == True:
      deliveryQ()
    else: 
      print("I do not understand your response. Please rephrase")


#6 
def bill():
  print("How can I help you with your bill?")
  userInput = ""
  
  answer1=''
  answer2=''
  answer3=''
  
  while (answer1 or answer2 or answer3)!=True:
    print("Options:pay bill, direct debit setup, high bill")
    userInput = input().lower()
    answer1=compare(userInput, paying_the_bill,0.5)
    answer2=compare(userInput,set_up_direct_debit,0.5)
    answer3=compare(userInput, high_bill,0.5)
    
    
    if answer1 == True:
      pay()
    elif answer2 == True:
      directdebit()
    elif answer3 == True:
      complaint()
    else: 
      print("I do not understand your response. Please rephrase")


#7
def accountOption():
  print("I think you need help about your account. How can I help you?")
  userInput = ""
  
  answer1=''
  answer2=''
  answer3=''
  
  while (answer1 or answer2 or answer3)!=True:
    print("Options:Contract, Device, More Options")
    userInput = input().lower()
    answer1=compare(userInput, contract,0.5)
    answer2=compare(userInput,device,0.5)
    answer3=compare(userInput,ac_more_options ,0.5)
    
    
    if answer1 == True:
      contractoption()
    elif answer2 == True:
      deviceoption()
    elif answer3 == True:
      ac_moreoptions()
    else: 
      print("I do not understand your response. Please rephrase")

#8        
def new_customerOptions():
      print("Welcome to Three. I am pleased to help you today.")
      userInput = ""
      answer1=''
      answer2=''
      answer3=''
      
      while (answer1 or answer2 or answer3)!=True:
        print("Options:New contract,About Products and Services, About the company")
        userInput = input().lower()
        answer1=compare(userInput, new_contract,0.5)
        answer2=compare(userInput,products_services_info,0.5)
        answer3=compare(userInput,about_the_company ,0.5)
        
        
        if answer1 == True:
          newcontract()
        elif answer2 == True:
          products()
        elif answer3 == True:
          aboutthecompany()
        else: 
          print("I do not understand your response. Please rephrase")
#-------------------------------------------------------------------------------------    
#9
def exist_customerOptions():
      
      print("Welcome back, how can I help you?")
      userInput = ""
      answer1=''
      answer2=''
      answer3=''
      answer4=''
      while (answer1 or answer2 or answer3 or answer4)!=True:
        print("Options:Bill, Account, Technical,more options")
        userInput = input().lower()
        answer1=compare(userInput,about_bill,0.5)
        answer2=compare(userInput,account, 0.5)
        answer3=compare(userInput,technical_issues,0.5)
        answer4=compare(userInput,more_options,0.5)
        
        if answer1 == True:
           bill()
        elif answer2 == True:
          accountOption()
        elif answer3 == True:
          technical()
        elif answer4 == True:
          moreoptions()
        else: 
          print("I do not understand your response. Please rephrase")

        

# 10
def existing_or_new():
      directions = ["Yes",'No']
      print("Are you an existing customer?")
      userInput = ""
      answer1=''
      answer2=''
      
      while (answer1 or answer2)!=True:
        print("Options: yes/no")
        userInput = input().lower()
        answer1=compare(userInput,existing_customer,0.5)
        answer2=compare(userInput,new_customer,0.5)
        #print(answer1 , answer2)
        if answer1 == True:
          exist_customerOptions()
        elif answer2 == True:
          new_customerOptions()
        
        else: 
          print("I do not understand your response. Please rephrase")

#---------------------------------------------------------------------------------------

if __name__ == "__main__":
    while True:
        print("Welcome to the Three Telecom Company!")
        print("Thank you for contacting us and we are pleased to help you.")
        print("I will ask some questions to be able to help you better.")
        print("Let's start with your name: ")
        name = input()
        print("Welcome, " +name+ ".")
        existing_or_new()
        break


Welcome to the Three Telecom Company!
Thank you for contacting us and we are pleased to help you.
I will ask some questions to be able to help you better.
Let's start with your name: 
bilaal
Welcome, bilaal.
Are you an existing customer?
Options: yes/no
Nope
I do not understand your response. Please rephrase
Options: yes/no
No, I am not a customer
Welcome to Three. I am pleased to help you today.
Options:New contract,About Products and Services, About the company
I want a new contract
Please go to our website and choose one of our deals or call our special number for new customers
Thank you for contacting us. Hope to see you again.


In [ ]:
test='I am a customer'
ans=compare(test, existing_customer, 0.5)
ans

array([[ True]])

In [ ]:
False==ans

array([[False]])

In [ ]:
if ans==True:
  print('hey')

hey


In [ ]:
# def response():
#   print('hey')
#   a='ok good'
#   exit()
#   return a
# def sorry():
#   b='sorry'
#   return b
# while True:
#   print('Hello, How are you ?')
#   userInput=input()
#   if userInput=='fine':
#     response()

#   else:
#     sorry()
#   break
  